version: '3.8'

services:

  api:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./feature_extract_api/Dockerfile
    environment:
      creds_hash: ${creds_hash}
    volumes:
      - ./feature_extract:/app/feature_extract
      - ./feature_extract_api:/app/feature_extract_api

