version: '3.8'

services:

  api:
    build:
      context: .
    environment:
      creds_hash: ""
      fgb_access_prefix: ""
    volumes:
      - source: /tmp
        target: /output
        type: bind
