version: '3.8'

services:

  api:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./feature_extract_api/Dockerfile
    environment:
      creds_hash: ${creds_hash}
    volumes:
      - type: bind
        source: ./feature_extract
        target: /app/feature_extract
      - type: bind
        source: ./feature_extract_api
        target: /app/feature_extract_api
