version: '3.8'

services:

  s3local:
    image: httpd:2.4
    volumes:
      - ./feature_extract/data:/usr/local/apache2/htdocs
    ports:
      - 8987:80

  api:
    image: tomfumb/bvsar-feature-extract-api
    ports:
      - 8023:80
    environment:
      # GDAL / FlatGeobuf config
      AWS_S3_ENDPOINT: s3local
      AWS_HTTPS: "NO"
      AWS_VIRTUAL_HOSTING: "FALSE"
      # API config
      fgb_access_prefix: /vsis3/fgb-data
      mvt_bucket_name: tiles
    command: uvicorn feature_extract_api.app:app --host 0.0.0.0 --port 80 --reload
    healthcheck:
      test: curl -s http://localhost/ > /dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 5s
      timeout: 1s
      retries: 10
    depends_on:
      - s3local

  ui:
    image: tomfumb/bvsar-feature-extract-ui
    build:
      context: .
      dockerfile: ./ui/Dockerfile
    ports:
      - 3023:80
    env_file:
      - ./ui/.env.docker
    volumes:
      - source: ./ui
        target: /app
        type: bind
    depends_on:
      api:
        condition: service_healthy
