name: CI Actions

on:
  push:
    branches:
      - '**'

jobs:

  validation:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: pre-commit deps
      run: pip install pre-commit

    - name: pre-commit config
      run: pre-commit install

    - name: pre-commit checks
      run: pre-commit run --all-files

  test-api:
    needs: validation
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      run: scripts/test.sh
